### ISSUE TITLE
Handle ANSI escapes in Logs

### ISSUE THREAD

**Issue by vifino** [moncho/dry#10]
Hello.

dry does not handle ANSI escapes (for color, etc..) in the logs.
They neither get stripped nor do they get interpreted.

Please do either, preferribly interpret them.

Otherwise, logs with them become quite a bit harder to read.

[This is how an example application using ANSI escapes is supposed to look like](https://puu.sh/nr1w5.png)
( Gin Gonic application, logs shown using `docker logs` )
[THis is the same application but logs shown using dry.](https://puu.sh/nr1E3.png)

**Comment by moncho** [comment]
Hi, 

Would you mind pasting here how **dry** is showing logs now? Is it just showing directly ANSI codes?

How often do you find yourself having this problem? It might not be an easy fix :)

**Comment by vifino** [comment]
One moment, updating the issue.

**Comment by moncho** [comment]
Fixed with https://github.com/moncho/dry/commit/1c1c925ce658fc8cd472933e22930c49da164914.

Update **dry** to version [v0.4-beta.8](https://github.com/moncho/dry/releases/tag/v0.4-beta.8)

**Comment by vifino** [comment]
While it doesn't interpret the escapes, I certainly appreciate them to be at least stripped.

Many thanks!
