### ISSUE TITLE
Quit keybind in help text is incorrect

### ISSUE THREAD

**Issue by MarkNBroadhead** [moncho/dry#100]
The global quit keybind is uppercase Q, not lowercase q. This incorrect in the help screen and has been fixed in https://github.com/moncho/dry/pull/99

**Comment by MarkNBroadhead** [comment]
Also, this is an amazing project and I'm so glad I found it today!!! Thank you for all your hard work!

**Comment by moncho** [comment]
Thanks for your kind words!!

**Comment by moncho** [comment]
Available in [v0.9-beta.10](https://github.com/moncho/dry/releases/tag/v0.9-beta.10).
