### ISSUE TITLE
APPVERSION 0.9-beta.10 error 404

### ISSUE THREAD

**Issue by idetoile** [moncho/dry#103]
Hello,
https://raw.githubusercontent.com/moncho/dry/master/APPVERSION
return 0.9-beta.10, but only 0.9-beta.9 is released, that lead to 404 error when trying to install from dryup.sh script.

PS: thanks for this great tool

**Comment by moncho** [comment]
Yes, sorry about it, there is a problem with the release process and it has not been published yet.

**Comment by moncho** [comment]
Release has been published, It should work now :)

**Comment by idetoile** [comment]
Ok, thanks, it works perfectly now :)
