### ISSUE TITLE
Unnessesary log

### ISSUE THREAD

**Issue by antonmedv** [moncho/dry#104]
Hi, thanks for awesome tool. But this logs:
```
INFO[0000] Launching dry
INFO[0005] Bye
```
are unessesary. Maybe remove them?

**Comment by moncho** [comment]
Hey, great that you like it :)

And yes, maybe is time to remove them.

**Comment by moncho** [comment]
Fixed on version [v0.10-beta.1](https://github.com/moncho/dry/releases/tag/v0.10-beta.1).
