### ISSUE TITLE
Some characters are not showing up properly

### ISSUE THREAD

**Issue by paraita** [moncho/dry#123]
I've just installed Dry on my machine (Archlinux) and I noticed some characters are not displayed properly.
I'm using the base Gnome Terminal application (using the Ubuntu Mono derivative Powerline Regular font).

![image](https://user-images.githubusercontent.com/1413759/68444012-b6564880-0179-11ea-9fa2-026b0099beaf.png)

I've tried reverting to a non Powerline font but the missing characters are still not showing up.

**Comment by moncho** [comment]
Hi @paraita, could it be that your font is missing some symbols? Specifically &#128153; and &#128051;

**Comment by paraita** [comment]
thanks for replying @moncho ! I've tried dry on my Apple laptop and I don't see any missing symbols so my problem is probably specific to Arch.
I've tried different fonts (Powerline and not Powerline) and I still have the problem.
I'll update the issue if I ever find the origin of the problem

**Comment by paraita** [comment]
Nevermind, I was missing some font as you explained. Fixed by installing the `noto-fonts-emoji` package and changed my font to Noto.
Thanks for the tool !
