### ISSUE TITLE
total crash when trying to see a log

### ISSUE THREAD

**Issue by thomasd3** [moncho/dry#153]
<img width="991" alt="Screenshot 2022-08-05 at 00 19 25" src="https://user-images.githubusercontent.com/14313218/182962482-ce4565e7-94ad-4b3d-9af7-14c9a35dc449.png">

**Comment by moncho** [comment]
It is a weird error, I cannot think a way where this might happen. Anyway I will add some checks to avoid crashing.

**Comment by thomasd3** [comment]
I've started to use Warp as a terminal emulator (https://github.com/warpdotdev/Warp) and I've noticed a couple oddities with Dry when using it, for example trying to paste a string when doing a search in the log gave some crashes, but not always. And it's hard to know what is what.
Next time I've something odd happen, I'll run the exact same thing with iTerm2 to narrow it down.

**Comment by moncho** [comment]
Cool, thanks @thomasd3!

I have added a partial fix to at least not crash dry.
