### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by gillesdemey** [moncho/dry#16]
It'd be awesome if dry was available via homebrew on OSX 👍

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by moncho** [comment]
A homebrew formula for **dry** has been created, for now on its own tap.

`brew tap moncho/dry`
`brew install dry`

Please give it a try and let me know if it does not work.

**Comment by gillesdemey** [comment]
It works, thanks! 🎉

**Comment by moncho** [comment]
Good :)
