### ISSUE TITLE
add enter/k key behavior like on htop

### ISSUE THREAD

**Issue by vyscond** [moncho/dry#18]
Make the `enter` key show the inspection is not much helpful. If you could trigger with the `enter` key an right or left menu with the list of commands that are now showed horizontally on the bottom would be more productive. 

Rebind `i` to trigger inspections makes more sense and bind `k` to stop container would be more fun :)

Besides that everything is perfect ;)

**Comment by moncho** [comment]
Thanks, using `enter` to show a menu with the command list is a great idea.

**Comment by moncho** [comment]
Hey @vyscond

A menu for container commands has been added, available pressing [Enter]. It has not been implemented exactly as you proposed it, but the basic idea is quite the same I would say.

**Inspect** has been rebind to [i]. Rebinding **kill** to [k] seems a bit dangerous, one wrong click and you have killed a running container (which might or might not be so fun, depending on how much you liked the container :).  

It would be really helpful if you could take a look and provide some feedback.

Available on version **v0.6-alpha.1**.

**Comment by vyscond** [comment]
@moncho thanks for taking the request mate! I see your point for the `k` bind. I thought about the UX used on the htop maybe? Pressing the key and actually open the left/right menu with the respective command selected? Anyhow this not a critical issue.

I will try  the alpha this days and give you feedback ASAP.

**Comment by vyscond** [comment]
@moncho I tested you update today. Pretty rad! Thanks for implement the feature :3
