### ISSUE TITLE
Docker 1.11+ dry not working using unix socket

### ISSUE THREAD

**Issue by xinity** [moncho/dry#20]
hy,

been trying to use dry with docker 1.11 (using libcontainerd) but it failed starting as dry searches for a unix socket in unix:///var/run/docker.sock.

docker socket now is located at : /var/run/docker/libcontainerd/docker-containerd.sock

any idea how to fix ?

**Comment by moncho** [comment]
Hi, 

You can set where the docker host is located with `-H`.

Try this, please:
 
`
dry -H unix:///var/run/docker/libcontainerd/docker-containerd.sock
`

**Comment by moncho** [comment]
Did it work? If so, I would close the issue.

**Comment by verzola** [comment]
Not working here.

**Comment by moncho** [comment]
Thanks, I will take a look.

**Comment by moncho** [comment]
I have a better understanding now on what it means to use libcontainerd. My suggestion above will never work.

Long story short, as it is working now, **dry** is not able to get information from **containerd**, since **containerd** uses gRPC for exposing functionality. **Dry** on the other hand uses the REST API exposed by the Docker engine.

So either **dry** learns to speak gRPC or a new project, dry-for-containerd or something, is created specifically. I would appreciate ideas and suggestions.

**Comment by verzola** [comment]
As this is the new default behavior of Docker >1.11, I think that it would be better to make dry learn to speak gRPC and move the actual version to a branch, and put a warning in the README.md for the people that are still using Docker <1.11. What do you think about this?

**Comment by moncho** [comment]
Thanks for sharing your thoughts :)

I agree with you that it would be better to make **dry** learn gRPC. Not so sure about moving away from the Docker engine completely. One thing to have clear is that **containerd** just knows about containers, it does not handle images, networks, etc... So when ***dry** connects to **containerd**  it will just be able to show container information.

I would expect that most of the times both **containerd** and **docker** daemons are going to be available in a host, and for this case **dry** should continue working as now. When just **containerd** is available, **dry** should use gRPC, and serve as an alternative to [containerd official CLI](https://github.com/docker/containerd/blob/master/docs/cli.md).

Makes sense?

**Comment by verzola** [comment]
Yeah, it makes a lot of sense... I didn't know that containerd was just about containers.
The docker daemon is still available in Docker >=1.11, isn't it? Now I don't get it why it is not possible to use Dry. I though that the Docker Daemon was not available anymore.

**Comment by moncho** [comment]
Yes, it should be possible to use **dry**. I am using it regularly with Docker 1.12 and have not found any problem so far. I am a bit clueless atm about where the problem might be.

Latest **dry** release (0.6-alpha.2) does a better job at reporting errors connecting to the Docker Daemon. If you could update, give it another try and paste here any error that might show, I might be able to figure it out.

**Comment by verzola** [comment]
Just to give you a update: dry is back to normal here. It is working fine with Docker 1.12.5.

**Comment by moncho** [comment]
Thanks for the update and great that it works again!

I will close the issue. A new issue will be created specifically for making *dry* learn gRPc.
