### ISSUE TITLE
Connection via TLS is not using default values

### ISSUE THREAD

**Issue by josetesan** [moncho/dry#23]
When the environment variable DOCKER_TLS_VERIFY is set to 1, docker client , by default, expects to find docker-service certificates inside ~/.docker folder.
Looks like dry ALSO expects a variable called DOCKER_CERT_PATH pointing to this folder.

From my point of view, there's two solutions :
1. Throw an error if DOCKER_TLS_VERIFY exists but there's no DOCKER_CERT_PATH variable
2. Search first inside ~/.docker folder to find certificates, and it there's none, throw an error about DOCKER_CERT_PATH not telling where they are. This is the one i like the most.

**Comment by moncho** [comment]
@josetesan Thanks for the bug report and the possible solutions. I had followed your suggestion and **dry** will now search for certificates in *~/.docker if no **DOCKER_CERT_PATH** is given.
