### ISSUE TITLE
Windows Instructions

### ISSUE THREAD

**Issue by pferrill** [moncho/dry#26]
I'd like to test this out on Windows but not sure how to proceed after downloading the binary.

**Comment by vyscond** [comment]
As far as i know i just have to run it from the CMD/Powershell.

**Comment by moncho** [comment]
Hi @pferrill, I have never tried it on Windows, but as @vyscond is saying I would expect that it works straight away from the CMD/Powershell.

Have you tried running the CMD and typing `dry` once installed? If so, is it not working? any error message that you can share?

Thanks

**Comment by pferrill** [comment]
There is no file named dry in the zip file.

**Comment by moncho** [comment]
Binaries can be downloaded from the [Releases](https://github.com/moncho/dry/releases) view. Download the one that fits your cpu arch (most likely [amd64](https://github.com/moncho/dry/releases/download/v0.6-alpha.5/dry-windows-amd64)), rename it to **dry** (this is optional) and move it to a folder in your **PATH**.

**Comment by pferrill** [comment]
Looks like that only works on Windows 10 - not Windows Server 2016 as the
Docker daemon isn't used on Windows Server.

**Comment by moncho** [comment]
It seems that Docker CLI for Windows uses named pipes for connecting to the Docker daemon, which is not supported by **dry**. 

But what should work is, if the Docker daemon is run exposing its TCP port,  running **dry** specifying the host. So something like this: `dry -H tcp://localhost:2375`. 

I would appreciate if you could give it a try and then share the results here.

**Comment by pferrill** [comment]
Got an error message that the target machine actively refused the
connection...

Might need a firewall rule?

**Comment by moncho** [comment]
I would say so, I read somewhere in the Docker docs for Windows about opening the firewall when exposing the port.

**Comment by vyscond** [comment]
@pferrill also check `docker-machine ip [machine_name]` on my case the localhost would not work since i'm using the virtualbox based docker :D

**Comment by moncho** [comment]
@pferrill did you manage to get it working? Can this issue be closed?

**Comment by pferrill** [comment]
I moved on so you can close it.

**Comment by moncho** [comment]
Closing it then, thanks.

**Comment by hansbogert** [comment]
I managed to get it working, colors were pretty messed up, at least in my case when running from PowerShell
![capturedry](https://cloud.githubusercontent.com/assets/2630900/24859993/d579925c-1df2-11e7-83da-2a1fe558d468.PNG)

**Comment by moncho** [comment]
@hansbogert Thanks for the feedback! It doesn't look pretty indeed :) 

**Dry**  uses [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) to show colors, but I have no idea if these are suppose to work in PowerShell.  Did you try using the Command Prompt? Does it look the same?

Anyway, I If you could please open a new issue, I can try to understand a bit better how terminal application are suppose to work on Windows and see if it can be fixed easily.
