### ISSUE TITLE
Add prune command

### ISSUE THREAD

**Issue by moncho** [moncho/dry#29]
[[Docker system prune]](https://docs.docker.com/engine/reference/commandline/system_prune/) command removes unused data.

Add the command to **dry**, it should be available on the Disk usage screen (see #28).

**Comment by moncho** [comment]
Available in release [v0.6-beta1](https://github.com/moncho/dry/releases/tag/v0.6-beta.1).

**Comment by 4goodapp** [comment]
What is the shortcut for the Disk Usage screen?

**Comment by moncho** [comment]
[F8]
