### ISSUE TITLE
Remove all exited containers

### ISSUE THREAD

**Issue by funkytaco** [moncho/dry#3]
If possible, I'd like a feature to remove all exited containers at once.

**Comment by moncho** [comment]
A helpful feature indeed :) 

Any idea to which key it should be mapped and how to describe it? My proposal:

```[Alt] + [E]: Remove exited containers```

**Comment by funkytaco** [comment]
That sounds good to me. I guess that makes more sense than `[Shift] + [E]`, which was my initial thought.

**Comment by moncho** [comment]
[Ctrl] + [E] is the key mapping for the command.

**Comment by funkytaco** [comment]
Nice, thanks.
