### ISSUE TITLE
Hint - new aur arch linux package

### ISSUE THREAD

**Issue by nogo** [moncho/dry#30]
The maintainer of the aur package "dry" made no update since a year. I made new one.
https://aur.archlinux.org/packages/dry-bin/ maybe you want to link it.

**Comment by moncho** [comment]
Cool, thanks!!

I dont know much about **arch**, does this change means that to install dry the command is now `yaourt -S dry-bin`?

**Comment by nogo** [comment]
Right! Would be an alternative to "dry". Btw nice tool 👍 I will try to be uptodate with this package.

**Comment by moncho** [comment]
Great, thanks for taking care ;)
