### ISSUE TITLE
Add more colors 

### ISSUE THREAD

**Issue by 4goodapp** [moncho/dry#37]
something like this 

![spectacle hm8460](https://cloud.githubusercontent.com/assets/6249230/25069718/f869d666-2278-11e7-9ec9-eeec161acec8.png)

white background for the selected container/image
green for running container
red for stopped one
and maybe an orange one for a starting/stopping container.

**Comment by moncho** [comment]
Your proposal is quite similar to ctop, right? 

I like the idea of making clearer the status of container, will give it a try to your proposal and see how it looks.

**Comment by 4goodapp** [comment]
> Your proposal is quite similar to ctop, right?

Exactely! :)

> I will give a try to your proposal and see how it looks.

That would be awsome :)

**Comment by moncho** [comment]
Please check the latest release (v0.8b1), will appreciate some feedback.

**Comment by 4goodapp** [comment]
I just check it, (sorry for the delay)
The container list only shows running containers. Not the stopped ones, making the green icons useless.

> On views with a list of elements, the item that has the cursor is shown by changing the background color of the column that identifies the item.

quote from release note.

> This isn't applied to the images list.

**Comment by moncho** [comment]
No problem and thanks for your feedback.

By default, **dry** shows running containers, pressing F2 changes it to show all containers, with the icon having a different color depending on the state of the container.

**Comment by 4goodapp** [comment]
OK, Thanks, I'll check it and will let you know.

**Comment by itwars** [comment]
What about having a external theme config file?

**Comment by moncho** [comment]
#15 also asks for having some kind of external configuration (in that case for custom keybindings), my opinion being that I rather keep dry as a single binary that is easy to install and remove.

Said that, if somebody is willing to give it a try I will be happy to add support for custom external configurations, but I prefer to dedicate time to improve the tool with features that could add more value to it.
