### ISSUE TITLE
rendering time is useless?

### ISSUE THREAD

**Issue by itwars** [moncho/dry#39]
Hi,

I think it's useless to display time in the ui, because the container is UTC, so the display time is wrong for most users?

render.go line 198.

or to make it great for everyone just add following steps in Dockerfile:
```dockerfile
# Add your own correct timezone!
RUN apk add tzdata && \
        cp /usr/share/zoneinfo/Europe/Paris /etc/localtime && \
        echo "Europe/Paris" >  /etc/timezone && \
        apk del tzdata
```
BR
Vincent

**Comment by moncho** [comment]
If *dry* is run in a Docker container it is true that the time might not be in the right timezone, but I am not convinced that setting a fixed timezone is useful for everybody.

The timezone can be set at runtime with:

`docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v /etc/localtime:/etc/localtime:ro moncho/dry`

**Comment by itwars** [comment]
Yes I agree with you, but this only work in Linux context, because sharing localtime on MacOS don't work. I think it's the same issue on Windows?

**Comment by moncho** [comment]
Yup, you are right, my suggestion will not work on every OS. Still I am not convinced that setting a timezone in the Dockerfile is the way to go. 

Any alternatives?
