### ISSUE TITLE
appui more space between MEM and NET columns

### ISSUE THREAD

**Issue by itwars** [moncho/dry#40]
Tiny visual issue : 

please add more space between MEM and NET columns  

![image](https://cloud.githubusercontent.com/assets/353918/26755420/2ee9b758-488d-11e7-9ae7-57e85375b6c5.png)

They are too close.

BR
Vincent

**Comment by moncho** [comment]
Thanks for reporting!!

Terminal width plays a role here, but it makes sense to try and give more room to these two columns.

**Comment by itwars** [comment]
Sur, resizing my screen make it better, but in some time, it's too close :)
