### ISSUE TITLE
Monitor mode + Help = Display issues

### ISSUE THREAD

**Issue by jeffersonbenson** [moncho/dry#41]
After launching Dry and beginning to explore some of it's features, I noticed that when in Monitor Mode and then bringing up the help menu there is a small display glitch. 

Steps to repeat:
1. Launch Dry
2. Enter Monitor mode
3. Press 'h' to enter the help menu

![drymonitorissue](https://user-images.githubusercontent.com/19256220/26950124-9aa61cc6-4c6a-11e7-8fc6-d91a1519d5c8.png)

**Comment by moncho** [comment]
Thanks for reporting!
