### ISSUE TITLE
Quitting logs (or other) should goto the container view, not back to home. 

### ISSUE THREAD

**Issue by todaywasawesome** [moncho/dry#42]
If I'm working within an image and look at the logs, or execute other commands, leaving sends me back to the dashboard. This is a bummer for my workflow, I want to work with one image at a time, not fallout to the dashboard everytime. 

PS cool tool, thanks for making it.

**Comment by moncho** [comment]
Thanks for reporting and great that you like the tool :)

**Comment by moncho** [comment]
Fixed in [v0.9-beta.3](https://github.com/moncho/dry/releases/tag/v0.9-beta.3).
