### ISSUE TITLE
Feature request: Toggle "follow" on "Fetch logs" view

### ISSUE THREAD

**Issue by slafs** [moncho/dry#46]
Thank you for this great tool!

Would be nice to have the ability to follow logs in the container's "Fetch logs" view. Currently I need to get out and back to that view (and hit `G`) to see newer logs, which combined with #42 makes the process pretty cumbersome.

**Comment by moncho** [comment]
Thanks for reporting it and great that you like the tool :)

Just a comment, there is no need to go to the menu to see the logs, from the container list, hitting `l`will take you to the logs.  This might make it a bit more tolerable, but definitely _follow_ capabilities will make the logs much more useful.

**Comment by slafs** [comment]
> from the container list, hitting lwill take you to the logs

ah, nice. Yeah, now returning back to container list (from log view) makes more sense :). Thanks!
