### ISSUE TITLE
killed containers do not disappear from list

### ISSUE THREAD

**Issue by funkytaco** [moncho/dry#5]
dry version 0.3-beta.9, build e0c03ae

Issue: killed containers do not disappear from list immediately, but show as exited when checked with an external tool.

To reproduce:

* launch dry
* K to kill a container
* See text "killed container with id f00..."
* container stays in the list of running containers for 30 seconds to 1 minute

I was expecting it to drop from the list like in 0.3-beta.6

Thanks.

**Comment by moncho** [comment]
Thanks for reporting. 

Is the behavior of **dry** different to the Docker CLI for [kill](https://docs.docker.com/engine/reference/commandline/kill/)? 

I guess that if you do ``` docker ps -a``` still shows the container **f00...**, right? Could you please try to kill the container using ``` docker kill```? 

The container list shown by **dry** should be the one reported by Docker. There was a change on 0.3-beta.6 to refresh the container list upon receiving events from the Docker daemon, which might explain the delay in updating.

**Comment by funkytaco** [comment]
Secondary issue:
Because it doesn't refresh, if I hit "kk", I get the following (because the container is either in the process of being deleted or doesn't exist):

    Error killing container 1225a521d95f. API error (500): Cannot kill container 1225a521d95f9526dc70103e2d69043d979484943851585c2f0b601af0dd4e31: Container 1225a521d95f9526dc70103e2d69043d97948494308:26:48

In answer to your question, if I do a `docker kill [container] && docker ps` in a second terminal, **dry** never updates. I "arrowed" up and down and waited about 45 seconds before I hit [F5] to refresh. Previously, I would kill containers in Docker UCP or a second terminal and dry seemed to update just fine.

From the [F2] screen that lists "non-running/killed" containers, if I do [CTRL-E] it says `Removing all stopped containers`. Then eventually it says `Removed all stopped containers` but this screen also acts the same way and doesn't refresh in a timely manner.

**dry** is talking to a remote Docker Swarm API. 0.3-beta.6 was working with the same swarm  just minutes before I upgraded.

I'm running OS X El Capitan version 10.11

 info from **dry**:

    Docker Host:         tcp://myhost:443                           Docker Version:  ucp/0.6.0
    Cert Path:           /Users/me/pathto/tls    APIVersion:      1.21
    Verify Certificate:  true                                                      OS/Arch/Kernel:  linux/amd64/

**Comment by moncho** [comment]
Thanks for the extended information :) 

My initial guess is that it is related to the use of Docker Swarm, maybe it behaves differently and it is not sending events. But I need to take a look.

**Comment by moncho** [comment]
Definitely related to Docker Swarm, see: https://github.com/docker/swarm/issues/1203

As a quick fix, **dry** will now auto-refresh every 15 seconds. Available in v0.3-beta.10.

@funkytaco Could you please check if **dry** is working as before?

**Comment by funkytaco** [comment]
Yes, thanks. All good now.

**Comment by funkytaco** [comment]
Hmm, I did a CTRL-E for killed containers, and it somehow killed [Docker UCP](https://www.docker.com/products/docker-universal-control-plane). I'm lucky this is a dev environment. dry has not done that before.

I'll open another ticket if it seems to be related to dry...

**Comment by funkytaco** [comment]
I've must've fat fingered something last time as Docker UCP seems fine this time when I tried to duplicate.
