### ISSUE TITLE
Memory usage is misleading

### ISSUE THREAD

**Issue by frol** [moncho/dry#51]
There was a long-standing bug in Docker stats util (https://github.com/moby/moby/issues/10824), which included caches into the memory usage reporting. While it was fixed recently in Docker 17.06 (https://github.com/docker/cli/pull/80), dry is still affected by the issue.

I think it is worth porting the new way of memory usage reporting from the https://github.com/docker/cli/pull/80.

**Comment by moncho** [comment]
Thanks!!
