### ISSUE TITLE
Timeout while trying to connect to Docker Daemon

### ISSUE THREAD

**Issue by pffreitas** [moncho/dry#57]
I'm getting a timeout while trying to connect to docker daemon. I'm running with my user which is part of "docker" group and does not requires sudo to access the docker socket. I've tried as root as well. 

I only could get it to work using version 0.3-beta.1, build 3816d77.  So I believe it may be a bug at stop showing loading screen as it does not seems to be a connection problem.

![screenshot from 2017-11-08 10-41-39](https://user-images.githubusercontent.com/913364/32549864-20d13572-c472-11e7-9266-35824a51c579.png)

**Comment by moncho** [comment]
Hi, not sure why it could be happening, the code to establish the connection with the Docker daemon hasn't really changed lately.

What is the Docker version?

**Comment by pffreitas** [comment]
I'm running docker 17.06-ce...

I did a little debugging session and on docker/connection.go:128 the docker client is returned without error. I'm having the feeling that it is simply a matter of signaling the channel to stop showing the loading screen at main.go. When does that should happen?

**Comment by moncho** [comment]
So it is not the Docker version. OS? 

After the connection is established, the signal is sent to stop showing the loading screen (by closing the channel), this happens on **main.go** as well, see [main.go:203](https://github.com/moncho/dry/blob/master/main.go#L203).

**Comment by pffreitas** [comment]
It Worked!!! 

I had too many containers.... 30secs was not enough to list and inspect each one. A `docker container prune` wiped away several unused containers and now I'm able to open it.

Btw, really nice job!! I'm looking forward to contribute to it if I have the opportunity. This should become native into the docker client. 

![screenshot from 2017-11-08 13-51-51](https://user-images.githubusercontent.com/913364/32559391-2aa8cc06-c48e-11e7-952d-1a07cb7b936b.png)

**Comment by moncho** [comment]
Ah, good, so it was just taking too long to start.

Great that you like it, contributions are very welcome :)

**Comment by moncho** [comment]
Can the issue be closed?

**Comment by pffreitas** [comment]
Yes, sure! 

Maybe we can think about creating some kind of paginated list for such cases. But if it makes sense, I believe it can be discussed in another issue.

**Comment by moncho** [comment]
Not sure if pagination is supported by the Docker API, but it might be worth checking. 

I have not been able to reproduce the problem with the naive approach of running 100+ containers on low-end hardware (i.e. rPi), **dry** loads quite fast, even from a remote machine. So there might be additional factors, besides the number of containers, to explain why did it happen.
