### ISSUE TITLE
ARM binaries?

### ISSUE THREAD

**Issue by hako** [moncho/dry#6]
Would be nice to provide ARM binaries for devices like the Raspberry Pi 2 & Raspberry Pi Model B+. I had to install Golang on B+ just to go get the binary. (Great job btw @moncho with dry)

**Comment by moncho** [comment]
Thanks :) feel like trying? It would be the first PR ever on this repo ;)

Changes should be done in the [Makefile](https://github.com/moncho/dry/blob/master/Makefile).

 To test: ```make release```, then check that binaries for ARM are also built.

**Comment by hako** [comment]
@moncho Made a PR #7

**Comment by moncho** [comment]
Thanks a lot, next release will include an ARM binary
