### ISSUE TITLE
Monitor mode's CPU percentage (crazy reading)

### ISSUE THREAD

**Issue by joereynolds** [moncho/dry#60]
See below:

![image](https://user-images.githubusercontent.com/9536682/36172000-7a4c6d52-10fc-11e8-9a8b-8b67321cd91e.png)

**Comment by moncho** [comment]
I need some more context.

- Is it running on Windows?
- Do you get the same reads with **Docker** CLI?
- Does it always happen? 

Thanks!

**Comment by joereynolds** [comment]
Hey @moncho 

If it happens again I'll let you know, I'm on Ubuntu 16.04 FYI :)

**Comment by moncho** [comment]
Cool, thanks.

I haven't seen anything obviously wrong in the code, but I will give it a more careful look at same point before closing the issue.

**Comment by moncho** [comment]
I’m closing this issue due to age. 

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/moncho/dry/releases/tag/v0.9-beta.8).

Thank you!
