### ISSUE TITLE
Color scheme on Windows

### ISSUE THREAD

**Issue by malys** [moncho/dry#62]
Hello,
Thank you for this great tool.
I 'm trying to use it on Windows 10 Pro.
It starts correctly but color theme is horrible. Text with the same color of background.
Is it possible to change color scheme (config file, ...)?

Bye

**Comment by moncho** [comment]
Hey, great that you like the tool :) Currently, it is not possible to change the color theme, sorry. 

The concept of color themes exists in the code, but it is not used everywhere. So, while it should be possible to add themes to the tool, not every UI component would be configurable, at least without major changes.

I will give it a thought, but it might not happen. Unless of course somebody else is willing to start working on it, I will gladly offer some guidance on where to do the changes.

Alternatively, is there not a way to change color themes in Windows terminal emulator?

**Comment by Memphizzz** [comment]
@malys The color scheme should also be configurable through your terminal. If you're using WSL for example the builtin command prompt which opens when you launch bash is very limited in terms of customization. For this you can use a more advanced terminal like WSLtty. WSLtty is based on minTTY and provides a user-friendly terminal for WSL which in contrast to cmd.exe allows customization of almost any aspect of a terminal.

**Comment by malys** [comment]
Sorry I didn't see comments.  Trying different workarounds, I didn't find solution.
Thx for your help.
