### ISSUE TITLE
Unable to build a project

### ISSUE THREAD

**Issue by vsobotka** [moncho/dry#67]
Hi, I wanted to jump in this project, play with it a bit and learn some go while solving some issues in the process. Unfortunately, I am not able to build this project and as I am new to Go and its ecosystem, I could use some help, if you would.

I have Go installed. I have cloned this repo to `$GOPATH/src`, but when I try to download dependencies with `dep ensure`, I get ths error:
```
Solving failure: No versions of github.com/docker/docker met constraints:
	d58ffa0364c04d03a8f25704d7f0489ee6cd9634: Could not introduce github.com/docker/docker@d58ffa0364c04d03a8f25704d7f0489ee6cd9634 due to a case-only variation: it depends on "github.com/Sirupsen/logrus", but "github.com/sirupsen/logrus" was already established as the case variant for that project root by the following other dependers:
	(root)
```
```
(6)	? attempt github.com/docker/docker with 14 pkgs; at least 1 versions to try
(6)	    try github.com/docker/docker@d58ffa0364c04d03a8f25704d7f0489ee6cd9634
(7)	✗   case-only variation in dependency on "github.com/Sirupsen/logrus"; "github.com/sirupsen/logrus" already established by:
(7)	  (root)
(7)	  github.com/docker/cli@master
(6)	    try github.com/docker/docker@v1.13.1
(7)	✗   github.com/docker/docker@v1.13.1 not allowed by constraint d58ffa0364c04d03a8f25704d7f0489ee6cd9634:
(7)	    d58ffa0364c04d03a8f25704d7f0489ee6cd9634 from (root)
(6)	    try github.com/docker/docker@v1.13.0
```

`make vendor` does not help either as it runs `dep ensure` before the `sed`. Running the `sed`  manually does not help.

I am running `Ubuntu 18.04`.

I tried to solve it last three days with no success. What am I missing? I tried to find the uppercase Sirupsen package in the dependencies, but I did not find it anywhere.

Thanks for your help. I can't wait to get it working and do some PRs.

**Comment by moncho** [comment]
Hi @vsobotka, since dependencies are already checked into the project there is no need to run **dep**. Try just running `make`, it should launch **dry** from your local version of the code. 

Please, let me know if it works, I am looking forward for those PRs :)

**Comment by vsobotka** [comment]
I have to run `go get` it and then go to `$GOPATH/src/github.com/moncho/dry` and there I should run `make` - it works that way. Is this the correct way to go about it?

It does not work when I clone it to `$GOPATH/src/dry` and run `make` on it. That gives me this error:
```
go run ./main.go
main.go:12:2: cannot find package "github.com/moncho/dry/app" in any of:
	/home/vaso/go/src/dry/vendor/github.com/moncho/dry/app (vendor tree)
	/home/vaso/.go/go1.10.2.linux-amd64/src/github.com/moncho/dry/app (from $GOROOT)
	/home/vaso/go/src/github.com/moncho/dry/app (from $GOPATH)
main.go:13:2: cannot find package "github.com/moncho/dry/appui" in any of:
	/home/vaso/go/src/dry/vendor/github.com/moncho/dry/appui (vendor tree)
	/home/vaso/.go/go1.10.2.linux-amd64/src/github.com/moncho/dry/appui (from $GOROOT)
	/home/vaso/go/src/github.com/moncho/dry/appui (from $GOPATH)
main.go:14:2: cannot find package "github.com/moncho/dry/docker" in any of:
	/home/vaso/go/src/dry/vendor/github.com/moncho/dry/docker (vendor tree)
	/home/vaso/.go/go1.10.2.linux-amd64/src/github.com/moncho/dry/docker (from $GOROOT)
	/home/vaso/go/src/github.com/moncho/dry/docker (from $GOPATH)
main.go:15:2: cannot find package "github.com/moncho/dry/ui" in any of:
	/home/vaso/go/src/dry/vendor/github.com/moncho/dry/ui (vendor tree)
	/home/vaso/.go/go1.10.2.linux-amd64/src/github.com/moncho/dry/ui (from $GOROOT)
	/home/vaso/go/src/github.com/moncho/dry/ui (from $GOPATH)
main.go:16:2: cannot find package "github.com/moncho/dry/version" in any of:
	/home/vaso/go/src/dry/vendor/github.com/moncho/dry/version (vendor tree)
	/home/vaso/.go/go1.10.2.linux-amd64/src/github.com/moncho/dry/version (from $GOROOT)
	/home/vaso/go/src/github.com/moncho/dry/version (from $GOPATH)
Makefile:23: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by moncho** [comment]
Great that you solved it, `go get` is correct, yes :)

With git clone would had worked as well by cloning the repo in the expected destination within the go workspace, that is `$GOPATH/src/github.com/moncho/dry`.

**Comment by vsobotka** [comment]
Ok then. Thanks for your time :)
