### ISSUE TITLE
Unable to connect to docker daemon 

### ISSUE THREAD

**Issue by Lerentis** [moncho/dry#68]
Hello there

i wanted to try dry today, but sadly i am running into an issue while trying to connect to my docker daemon.

if i run `TERM=xterm dry -H /var/run/docker.sock -m` dry terminates with the message
```
ERROR[0000] There was an error launching dry              error="Error retrieving container list: Cannot connect to the Docker daemon at tcp://localhost:2375/var/run/docker.sock. Is the docker daemon running?"
```
in `journalctl -u docker` i can see the following message corresponding to the time i launched dry:

```
Jun 01 00:48:05 Muninn dockerd[598]: time="2018-06-01T00:48:05.290135583+02:00" level=error msg="Handler for GET /v1.31/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Jun 01 00:48:05 Muninn dockerd[598]: http: multiple response.WriteHeader calls
``` 

Am i doing something wrong?

docker version:
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   f150324782
 Built:        Wed May 16 22:27:45 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   f150324782
  Built:        Wed May 16 22:28:17 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
Dry Version: 0.9-beta.4

**Comment by Lerentis** [comment]
Hey @moncho 

Yeah the user is in the docker group.

Running dry without specifying the host works, but isn't it connecting against the same socket? Also i cloud swear i tried it last night but my memories could be wrong.
Anyway thank you for your reply and this software. will spread the word about your project (:

**Comment by moncho** [comment]
The problem was that the protocol was missing from the host definition. This should work:
`TERM=xterm dry -H unix:///var/run/docker.sock -m`
