### ISSUE TITLE
Windows immediately stops with message INFO[0000] Bye

### ISSUE THREAD

**Issue by JVecsei** [moncho/dry#69]
Using the newest released binary (also tried the one before the newest) I get the message "INFO[0000] Bye" instantly after typing "dry".

Docker started properly and is running but I can't seem to get this running. Sadly I don't get any detailed error messages.

**Comment by moncho** [comment]
Hi, 

Could you please try to redirect stderr output to a file and copy the content here: `dry 2&> dry-complains.txt`

Also, are you trying to run **dry** on Windows?

**Comment by JVecsei** [comment]
Hi thanks for your quick response. Yes sorry should have written that in my text. I am trying to run dry on Windows.

**Comment by JVecsei** [comment]
Ok, it works now. Had to activate: `Expose daemon on tcp://localhost:2375 without TLS` in the docker settings. Sadly the color theme makes it unusable on windows. But there is already another issue for that.

Thanks for your help.
