### ISSUE TITLE
Dry latest closing just after launch

### ISSUE THREAD

**Issue by remipassmoilesel** [moncho/dry#74]
Hi,
When I launch the latest version of dry, it close immediately after. I tried to install it manually and with the dry-up.sh script, without success. But if I install v0.9-beta.3 it works normally.

With v0.9-beta.5:
```
$ dry
INFO[0000] Launching dry
INFO[0000] Bye
```

My configuration (Xubuntu Bionic):
```
$ docker -v
Docker version 17.12.1-ce, build 7390fc6

$ uname -a
Linux XXXXX 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks for this tool !

**Comment by moncho** [comment]
I will close the issue then ;)

**Comment by likhter** [comment]
What about docker version `1.12.6`? I checked [this chart](https://docs.docker.com/develop/sdk/#api-version-matrix) and tried `DOCKER_API_VERSION='1.24' dry` but still
```
❯ docker -v
Docker version 1.12.6, build 78d1802

~
❯ DOCKER_API_VERSION='1.24' dry
INFO[0000] Launching dry
INFO[0000] Bye
```

@moncho
