### ISSUE TITLE
dry exit without error

### ISSUE THREAD

**Issue by stef-pellegrino** [moncho/dry#79]
My host 
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Docker side :
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.1
  Git commit:	7390fc6
  Built:	Wed Feb 28 17:46:05 2018
  OS/Arch:	linux/amd64
  Experimental:	false

I run
$ dry
and get
**INFO[0000] Launching dry                                
INFO[0000] Bye**

I tried **sudo dry -H unix:///var/run/docker.sock** too, without success

Any ideas ?

**Comment by moncho** [comment]
Hi, see #74.

`DOCKER_API_VERSION='1.35' dry` should work. 

And I guess an error message would help.

**Comment by stef-pellegrino** [comment]
Yes, it works ...
Thanks (and sorry for missing this #74)

**Comment by moncho** [comment]
No problem at all!! it is a good reminder that **dry** should do a better job a reporting this specific error, it is not that uncommon.

Cheers
