### ISSUE TITLE
Add configurable interval for monitor mode

### ISSUE THREAD

**Issue by Memphizzz** [moncho/dry#87]
Hi,

first of all, thank you very much for dry! It's an amazing piece of software. I especially like the monitor mode. 

Would it be possible to add a configurable interval on how quickly the monitor refreshes? Because if you have dry running for a few days, the consumed CPU time (TIME+) is huge, I guess by limiting the refresh rate to lets say every 30 seconds would improve that.

Thanks in advance and keep up the great work!

**Comment by Memphizzz** [comment]
Hi,

thanks, that will help it think.
I've just tested this:

Started both htop and dry in a horizontally tiled tmux window and let them run for a few hours:
After 21.86h this was the result:
`
PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command 
68710 memphiz   20   0  114832  15996   8984 S   1.7  0.4  23:40.15 dry
68708 root      20   0   28528   5080   3892 S   0.7  0.1  11:05.88 htop
`
You can see that dry used more than double the cpu time of htop. It's usually using 2% CPU on this particular VM constantly (Ubuntu Server 18.04.1 LTS - 8 Cores/4GB RAM).  My guess is that by reducing the amount of refreshes this will reduce the constant CPU usage to about 0-1% and reduce overall CPU time to be even below htop.

> increase in CPU time consumption when running for a long period of time is most likely an indication of dry misusing resources
I don't know if I agree with this. Isn't CPU time the total time the CPU used for this process from start until now and must go up over a long period of time? This would make sense to me if we would be talking about RAM usage but any process's CPU time will be huge if you let it run long enough (and it actually does something). The only question is how quickly that happens, which depends on how much work is being done. So by being able to set the screen refresh interval manually, anyone should be able to meet his/her prefered CPU usage/time limit, right?

Regards,
MemphiZ

**Comment by moncho** [comment]
Thanks for the test @Memphizzz!!

> I don't know if I agree with this. Isn't CPU time the total time the CPU used for this process from start until now and must go up over a long period of time? This would make sense to me if we would be talking about RAM usage but any process's CPU time will be huge if you let it run long enough (and it actually does something). The only question is how quickly that happens, which depends on how much work is being done. So by being able to set the screen refresh interval manually, anyone should be able to meet his/her prefered CPU usage/time limit, right?

I misunderstood your initial comment and thought you were saying that when left running for a while **dry** average CPU usage was increasing but you were actually talking about total CPU time, which as you said it always increases with time :) 

Anyway, I agree that reducing the refresh interval might help a bit with the CPU usage. Next release will include this.

Cheers

**Comment by Memphizzz** [comment]
Awesome, thank you very much!

**Comment by moncho** [comment]
Added in [v0.9-beta.9](v0.9-beta.9).

**Comment by Memphizzz** [comment]
Would it be possible to give this a command line parameter as well? For example: dry -m -r 5000 ?

**Comment by Memphizzz** [comment]
Also please make it refresh once, after you've entered a value..

**Comment by moncho** [comment]
> Would it be possible to give this a command line parameter as well? For example: dry -m -r 5000 ?

@Memphizzz Could you please open a new Issue for this?

**Comment by Memphizzz** [comment]
@moncho Sure thing. Here you go: https://github.com/moncho/dry/issues/94

**Comment by Memphizzz** [comment]
Now that this is added, here is a updated performance overview with the refresh interval set to 5000ms.

```
 PID CMD                                          STARTED     TIME %MEM %CPU
48339 htop                        Sun Mar  3 18:15:34 2019 00:15:09  0.0  1.3
48340 dry                         Sun Mar  3 18:15:34 2019 00:04:08  0.2  0.3

```

Very good improvements in terms of both, constant CPU usage and CPU time. Memory consumption unchanged (good).

**Comment by moncho** [comment]
Thanks for sharing!!
