### ISSUE TITLE
Feature Request: auto refresh main screen

### ISSUE THREAD

**Issue by eduvv** [moncho/dry#88]
I leave my terminal open 24/7, instead of hitting the F5 key every time, can we have an autorefresh for the main screen, so I can see how long my containers are running or if they are disappearing randomly. Just like monitor-mode auto refreshes

**Comment by moncho** [comment]
**dry** does some effort to keep information up-to-date by listening to events reported by the **Docker** daemon and updating information whenever it interprets that something that happened might change the state, e.g. container creation, container deletion. 

If you are observing that, for example, in the container list a container is being shown while `docker ps` does not show the same container, then it might be that the refresh logic is not working properly and it should be reviewed.

**Comment by eduvv** [comment]
I checked again and when a container is stopped or killed the main list in dry doesn't update unleds some action is done like sorting or if you scroll through the list. 
My request was indeed to have an auto update of the time-alive (so without waiting for events and instead force refreshing every x seconds) but it seems that the refresh logic isn't working as expected.

**Comment by moncho** [comment]
Thanks for the update! 

A bug it is then.

**Comment by moncho** [comment]
Better support to refresh on container change has been added in [v0.9-beta.9](v0.9-beta.9).

Autorefreshing is not yet supported, but a new specific issue for it will be created.
