### ISSUE TITLE
Feature Request: Configurable Shortcuts or change 'q'

### ISSUE THREAD

**Issue by Memphizzz** [moncho/dry#89]
This might only be me but muscle-memory trained me to press 'q' when I want to exit an interactive application. The same applies when I go and have a look at the logs in dry. Once I'm done checking the log I instantly hit 'q', which in this case closes dry. The intent was to go back to the menu though.
Therefore it would be great to have the option to either change 'q' to be 'Esc' and 'Esc' to be 'F10' for example, so I don't accidentally keep closing dry.
Alternatively making it dry quit on capital q (like displayed) would at least not close dry and remind me to use 'Esc'.

**Comment by Memphizzz** [comment]
Or, of course, don't quit using q when viewing logs but behave like I pressed 'Esc' once :)

**Comment by moncho** [comment]
Good suggestion.

I would propose to limit the scope and just change **dry** to just use capital **Q** to quit, keeping it as a global key-bind.

I would prefer to not use **q** to quit logs for now, there might be a future use for it, and **Esc** works just fine.

And having configurable shortcuts is fine with me, but it is not something I am willing to do, PR are always welcome, tho ;)

**Comment by canselcik** [comment]
Recently found out about `dry`, had been using `ctop` on and off until now. This change would make me switch to using `dry` for good.

**Comment by moncho** [comment]
Changed in [v0.9-beta.9](v0.9-beta.9).
