### ISSUE TITLE
Descending sort

### ISSUE THREAD

**Issue by lazee** [moncho/dry#90]
I really love dry. It's so much better than webguis for managing Docker.

However, there is one feature I'm missing: descending sort (Have I missed it?).

I would like to see the images that take up most space for instance.

**Comment by moncho** [comment]
Great that you like the tool, @lazee!!

In **dry**, wherever a list is shown, you can change the column used to sort by pressing **F1**. To sort by image size, in the images list, press **F1** three times and you should have the list ordered by size.

Sort is always done in descending order.

**Comment by lazee** [comment]
ait. Thanks :)

**Comment by moncho** [comment]
Sorry, I meant to say that sorting is done in ascending order. 

Switching between and ascending and descending sort is still missing good UX.

**Comment by lazee** [comment]
I found out that I can use `g` to scroll to the bottom. That is good enough for me :)
