### ISSUE TITLE
Can't delete images

### ISSUE THREAD

**Issue by im-n1** [moncho/dry#91]
I don't know why but I can't delete random images. I tried to delete those without a tag but no luck. CTRL-E/F doesn't work. If I try to delete them via docker command `docker image rm XXX` everything works seasmlessly.

Removing dangling images also doesn't work.

Version: dry version 0.9-beta.8, build 21a57510
Docker version 18.09.2, build 6247962

My case:
![image](https://user-images.githubusercontent.com/198654/53454150-908f7600-3a26-11e9-8b87-d4707de22794.png)

Dry has no debug output so I'm sorry I can't provide more info.

**Comment by im-n1** [comment]
Update: when I try to delete an image it changes it's hash but nothing happens.

**Comment by moncho** [comment]
Hi, 
A couple of questions:
Does it happen with all images or just the intermediate or danglig images (those shown as **<none>:<none>**)? 
Is the image list shown by **dry** the same as running `docker images -a`?

I would suggest to try using **Remove dangling** a few times, it should eventually remove them all.

**Comment by im-n1** [comment]
1. It happends with all images shown by dry.
2.
Well....

```
~ » docker images -a | wc -l
253
```

**Comment by im-n1** [comment]
Update:
When I ran `docker system prune --all` it removed a lot of stuff (unlike the same command without the `--all` argument) and now  `docker images -a | wc -l` shows 36. I guess the conclusion here is:

1) should dry remove all intermediate images under an image when the user hits CTRL F?
2) Should we add another action to Images pane to trigger `docker system prune --all`?

**Comment by moncho** [comment]
Thanks for the update!

1. The way **Remove dangling** works now is, first it searches for all the **dangling** images and then it removes. It is very possible that removing **dangling** images creates new ones. 

New functionality could be added to remove all unused images (not just the dangling ones), which would be equivalent to calling `docker images prune -a`.

2. There is already a **Prune** pane. Pressing **F8** will take you to it and from there you can see what prune will do and run it pressing **p**

**Comment by moncho** [comment]
Fixed in [v0.9-beta.9](v0.9-beta.9).
