### ISSUE TITLE
no luck

### ISSUE THREAD

**Issue by CaptainSkywave** [moncho/dry#97]
On a rock64 board (arm), when I do this:
`curl -sSf https://moncho.github.io/dry/dryup.sh | sudo sh`
it starts downloading and then I get this:
`~ $ curl -sSf https://moncho.github.io/dry/dryup.sh | sudo sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    10  100    10    0     0     19      0 --:--:-- --:--:-- --:--:--    19
aar
sh: 233: CFG_CPUTYPE: parameter not set`

**Comment by CaptainSkywave** [comment]
ok - found out that I can just download the bin file, do:
sudo chmod a+x <FILE_NAME>
then:
sudo ./<FILE_NAME>

**Comment by moncho** [comment]
Hi @CaptainSkywave,

can you run `uname -m` and copy the ouput here, please?

Cheers

**Comment by CaptainSkywave** [comment]
aarch64

**Comment by moncho** [comment]
Thanks!! 

Issue #98 has been created to support Arm64.

**Comment by CaptainSkywave** [comment]
Thanks.

**Comment by Codelica** [comment]
Just FYI... this change doesn't seem to have made it into https://moncho.github.io/dry/dryup.sh yet.  Not sure if that's on purpose for now. 

Using https://raw.githubusercontent.com/moncho/dry/development/dryup.sh does work fine for aarch64 though.

Thanks!

**Comment by moncho** [comment]
Thanks for reporting @Codelica, I had forgotten to update the **gh-pages** branch, which has its own copy of the script. It should work now.
